### PR TITLE
Schinese Update

### PR DESCRIPTION
**Pull request by MC-AS-Huier**
I submitted the text I translated with @xiaojinna  for PR

### CODE REVIEW

**Comment by music-discussion** [comment]
huh, its not letting me accept the request weird.

**Comment by MC-AS-Huier** [comment]
In the future, you can not, first agree to PR, you can then update, otherwise it is easy to lead to conflict

**Comment by MC-AS-Huier** [comment]
By the way, can you fix the bugs first before the career update, otherwise the game

**Comment by music-discussion** [comment]
wdym career update?

**Pull request merged**
