### PR TITLE
CSV Update

### PR DESCRIPTION
**Pull request by MC-AS-Huier**
I have roughly corrected the translation in it, but I'm tired now and have to rest, so I can't correct all the mistakes

### CODE REVIEW

**Comment by music-discussion** [comment]
Also, leaving a comma at the end causes it to show up as INVALID in game :/

**Comment by music-discussion** [comment]
also why are you always reverting my changes like tf

**Comment by MC-AS-Huier** [comment]
> 此外，在末尾留下逗号会导致它在游戏中显示为无效：/
In fact, the file takes this into account by automatically displaying the English language when the column after the "," is empty

**Comment by MC-AS-Huier** [comment]
> > 此外，在末尾留下逗号会导致它在游戏中显示为无效：/
> > In fact, the file takes this into account by automatically displaying the English language when the column after the "," is empty

Snipaste_2022-11-01_17-09-04
This is the relevant code snippet

**Pull request merged**
